name: Build and deploy
on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/**'
      - 'public/**'
      - 'src/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Build
        run: |
          yarn install --frozen-lockfile
          yarn build

          cd build
          rm -rf assets
          touch .nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: gh-pages
          folder: build
          single-commit: true
